# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDisplay(object):
    def setupUi(self, FormDisplay):
        FormDisplay.setObjectName("FormDisplay")
        FormDisplay.resize(668, 849)
        self.gridLayout = QtWidgets.QGridLayout(FormDisplay)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(FormDisplay)
        self.groupBox_3.setMinimumSize(QtCore.QSize(650, 175))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 175))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.labelFile = QtWidgets.QLabel(self.groupBox_3)
        self.labelFile.setText("")
        self.labelFile.setObjectName("labelFile")
        self.gridLayout_2.addWidget(self.labelFile, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.labelObject = QtWidgets.QLabel(self.groupBox_3)
        self.labelObject.setText("")
        self.labelObject.setObjectName("labelObject")
        self.gridLayout_2.addWidget(self.labelObject, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.labelValue = QtWidgets.QLabel(self.groupBox_3)
        self.labelValue.setText("")
        self.labelValue.setObjectName("labelValue")
        self.gridLayout_2.addWidget(self.labelValue, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.labelRa = QtWidgets.QLabel(self.groupBox_3)
        self.labelRa.setText("")
        self.labelRa.setObjectName("labelRa")
        self.gridLayout_2.addWidget(self.labelRa, 3, 1, 1, 1)
        self.labelDec = QtWidgets.QLabel(self.groupBox_3)
        self.labelDec.setText("")
        self.labelDec.setObjectName("labelDec")
        self.gridLayout_2.addWidget(self.labelDec, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.labelX = QtWidgets.QLabel(self.groupBox_3)
        self.labelX.setText("")
        self.labelX.setObjectName("labelX")
        self.gridLayout_2.addWidget(self.labelX, 4, 1, 1, 1)
        self.labelY = QtWidgets.QLabel(self.groupBox_3)
        self.labelY.setText("")
        self.labelY.setObjectName("labelY")
        self.gridLayout_2.addWidget(self.labelY, 4, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FormDisplay)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 650))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(FormDisplay)
        QtCore.QMetaObject.connectSlotsByName(FormDisplay)

    def retranslateUi(self, FormDisplay):
        _translate = QtCore.QCoreApplication.translate
        FormDisplay.setWindowTitle(_translate("FormDisplay", "Display"))
        self.groupBox_3.setTitle(_translate("FormDisplay", "Information"))
        self.label.setText(_translate("FormDisplay", "File"))
        self.label_2.setText(_translate("FormDisplay", "Object"))
        self.label_3.setText(_translate("FormDisplay", "Value"))
        self.label_4.setText(_translate("FormDisplay", "WCS"))
        self.label_5.setText(_translate("FormDisplay", "Physical"))
        self.groupBox.setTitle(_translate("FormDisplay", "Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormDisplay = QtWidgets.QWidget()
    ui = Ui_FormDisplay()
    ui.setupUi(FormDisplay)
    FormDisplay.show()
    sys.exit(app.exec_())
