# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animate.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 677)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 112))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(50, 20))
        self.label.setMaximumSize(QtCore.QSize(50, 20))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.animate_file_name = QtWidgets.QLineEdit(self.groupBox)
        self.animate_file_name.setEnabled(False)
        self.animate_file_name.setObjectName("animate_file_name")
        self.gridLayout_2.addWidget(self.animate_file_name, 0, 1, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(50, 20))
        self.label_2.setMaximumSize(QtCore.QSize(50, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.animate_x = QtWidgets.QLineEdit(self.groupBox)
        self.animate_x.setEnabled(False)
        self.animate_x.setObjectName("animate_x")
        self.gridLayout_2.addWidget(self.animate_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(50, 20))
        self.label_3.setMaximumSize(QtCore.QSize(50, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.animate_y = QtWidgets.QLineEdit(self.groupBox)
        self.animate_y.setEnabled(False)
        self.animate_y.setObjectName("animate_y")
        self.gridLayout_2.addWidget(self.animate_y, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(50, 20))
        self.label_4.setMaximumSize(QtCore.QSize(50, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 4, 1, 1)
        self.animate_value = QtWidgets.QLineEdit(self.groupBox)
        self.animate_value.setEnabled(False)
        self.animate_value.setObjectName("animate_value")
        self.gridLayout_2.addWidget(self.animate_value, 1, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(571, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.animate_display = gingaWidget(self.groupBox_2)
        self.animate_display.setObjectName("animate_display")
        self.gridLayout.addWidget(self.animate_display, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMinimumSize(QtCore.QSize(611, 84))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 84))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.animate_tim_line = QtWidgets.QSlider(self.groupBox_3)
        self.animate_tim_line.setPageStep(1)
        self.animate_tim_line.setOrientation(QtCore.Qt.Horizontal)
        self.animate_tim_line.setObjectName("animate_tim_line")
        self.gridLayout_3.addWidget(self.animate_tim_line, 0, 0, 1, 7)
        spacerItem = QtWidgets.QSpacerItem(86, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.animate_goFirst = QtWidgets.QPushButton(self.groupBox_3)
        self.animate_goFirst.setObjectName("animate_goFirst")
        self.gridLayout_3.addWidget(self.animate_goFirst, 1, 1, 1, 1)
        self.animate_goPrevious = QtWidgets.QPushButton(self.groupBox_3)
        self.animate_goPrevious.setObjectName("animate_goPrevious")
        self.gridLayout_3.addWidget(self.animate_goPrevious, 1, 2, 1, 1)
        self.animate_playPause = QtWidgets.QPushButton(self.groupBox_3)
        self.animate_playPause.setObjectName("animate_playPause")
        self.gridLayout_3.addWidget(self.animate_playPause, 1, 3, 1, 1)
        self.animate_goNext = QtWidgets.QPushButton(self.groupBox_3)
        self.animate_goNext.setObjectName("animate_goNext")
        self.gridLayout_3.addWidget(self.animate_goNext, 1, 4, 1, 1)
        self.animate_goLast = QtWidgets.QPushButton(self.groupBox_3)
        self.animate_goLast.setObjectName("animate_goLast")
        self.gridLayout_3.addWidget(self.animate_goLast, 1, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 6, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Animate"))
        self.groupBox.setTitle(_translate("Form", "Information"))
        self.label.setText(_translate("Form", "File"))
        self.label_2.setText(_translate("Form", "X"))
        self.label_3.setText(_translate("Form", "Y"))
        self.label_4.setText(_translate("Form", "Value"))
        self.groupBox_2.setTitle(_translate("Form", "Image"))
        self.groupBox_3.setTitle(_translate("Form", "Controls"))
        self.animate_goFirst.setText(_translate("Form", "<<"))
        self.animate_goPrevious.setText(_translate("Form", "<"))
        self.animate_playPause.setText(_translate("Form", "|>"))
        self.animate_goNext.setText(_translate("Form", ">"))
        self.animate_goLast.setText(_translate("Form", ">>"))


from gingawidgetFile import gingaWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
