# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(954, 659)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.disp_chart = matplotlibWidget(self.groupBox)
        self.disp_chart.setObjectName("disp_chart")
        self.gridLayout.addWidget(self.disp_chart, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.file_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.file_path.setEnabled(False)
        self.file_path.setObjectName("file_path")
        self.gridLayout_6.addWidget(self.file_path, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 0, 1, 1)
        self.get_file = QtWidgets.QPushButton(self.groupBox_2)
        self.get_file.setObjectName("get_file")
        self.gridLayout_6.addWidget(self.get_file, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.variabl_index = QtWidgets.QComboBox(self.groupBox_3)
        self.variabl_index.setObjectName("variabl_index")
        self.gridLayout_3.addWidget(self.variabl_index, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        self.label_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.compair_index = QtWidgets.QComboBox(self.groupBox_3)
        self.compair_index.setObjectName("compair_index")
        self.gridLayout_3.addWidget(self.compair_index, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setMinimumSize(QtCore.QSize(20, 20))
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.compair2_index = QtWidgets.QComboBox(self.groupBox_3)
        self.compair2_index.setObjectName("compair2_index")
        self.gridLayout_3.addWidget(self.compair2_index, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(20, 20))
        self.label_6.setMaximumSize(QtCore.QSize(20, 20))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.aperture = QtWidgets.QComboBox(self.groupBox_3)
        self.aperture.setObjectName("aperture")
        self.gridLayout_3.addWidget(self.aperture, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.x_values = QtWidgets.QComboBox(self.groupBox_4)
        self.x_values.setObjectName("x_values")
        self.gridLayout_5.addWidget(self.x_values, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.do_phase = QtWidgets.QGroupBox(self.groupBox_2)
        self.do_phase.setEnabled(False)
        self.do_phase.setCheckable(True)
        self.do_phase.setChecked(False)
        self.do_phase.setObjectName("do_phase")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.do_phase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.do_phase)
        self.label_4.setMinimumSize(QtCore.QSize(25, 20))
        self.label_4.setMaximumSize(QtCore.QSize(25, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.t_0 = QtWidgets.QDoubleSpinBox(self.do_phase)
        self.t_0.setMinimum(-1e+32)
        self.t_0.setMaximum(1e+31)
        self.t_0.setObjectName("t_0")
        self.gridLayout_2.addWidget(self.t_0, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.do_phase)
        self.label_5.setMinimumSize(QtCore.QSize(25, 20))
        self.label_5.setMaximumSize(QtCore.QSize(25, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.period = QtWidgets.QDoubleSpinBox(self.do_phase)
        self.period.setMinimum(0.0)
        self.period.setMaximum(1e+31)
        self.period.setObjectName("period")
        self.gridLayout_2.addWidget(self.period, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.do_phase, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 6, 0, 1, 1)
        self.plot = QtWidgets.QPushButton(self.groupBox_2)
        self.plot.setObjectName("plot")
        self.gridLayout_6.addWidget(self.plot, 6, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Graph"))
        self.groupBox.setTitle(_translate("Form", "Graph"))
        self.groupBox_2.setTitle(_translate("Form", "Settings"))
        self.get_file.setText(_translate("Form", "Add"))
        self.groupBox_3.setTitle(_translate("Form", "Ys"))
        self.label.setText(_translate("Form", "V"))
        self.label_2.setText(_translate("Form", "C"))
        self.label_3.setText(_translate("Form", "C2"))
        self.label_6.setText(_translate("Form", "Ap"))
        self.groupBox_4.setTitle(_translate("Form", "Xs"))
        self.do_phase.setTitle(_translate("Form", "Phase Calculatoe"))
        self.label_4.setText(_translate("Form", "T0"))
        self.label_5.setText(_translate("Form", "P"))
        self.plot.setText(_translate("Form", "Plot"))


from matplotlibwidgetFile import matplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
