# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'header_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(359, 578)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.hcalc_jd = QtWidgets.QGroupBox(Form)
        self.hcalc_jd.setMaximumSize(QtCore.QSize(16777215, 76))
        self.hcalc_jd.setCheckable(True)
        self.hcalc_jd.setObjectName("hcalc_jd")
        self.gridLayout_77 = QtWidgets.QGridLayout(self.hcalc_jd)
        self.gridLayout_77.setObjectName("gridLayout_77")
        self.label_51 = QtWidgets.QLabel(self.hcalc_jd)
        self.label_51.setObjectName("label_51")
        self.gridLayout_77.addWidget(self.label_51, 0, 0, 1, 1)
        self.hcalc_jd_time = QtWidgets.QComboBox(self.hcalc_jd)
        self.hcalc_jd_time.setObjectName("hcalc_jd_time")
        self.gridLayout_77.addWidget(self.hcalc_jd_time, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.hcalc_jd, 0, 0, 1, 2)
        self.hcalc_airmass = QtWidgets.QGroupBox(Form)
        self.hcalc_airmass.setMaximumSize(QtCore.QSize(16777215, 190))
        self.hcalc_airmass.setCheckable(True)
        self.hcalc_airmass.setObjectName("hcalc_airmass")
        self.gridLayout_78 = QtWidgets.QGridLayout(self.hcalc_airmass)
        self.gridLayout_78.setObjectName("gridLayout_78")
        self.label_59 = QtWidgets.QLabel(self.hcalc_airmass)
        self.label_59.setObjectName("label_59")
        self.gridLayout_78.addWidget(self.label_59, 0, 0, 1, 1)
        self.hcalc_airmass_time = QtWidgets.QComboBox(self.hcalc_airmass)
        self.hcalc_airmass_time.setObjectName("hcalc_airmass_time")
        self.gridLayout_78.addWidget(self.hcalc_airmass_time, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.hcalc_airmass)
        self.label_52.setObjectName("label_52")
        self.gridLayout_78.addWidget(self.label_52, 1, 0, 1, 1)
        self.hcalc_airmass_ra = QtWidgets.QComboBox(self.hcalc_airmass)
        self.hcalc_airmass_ra.setObjectName("hcalc_airmass_ra")
        self.gridLayout_78.addWidget(self.hcalc_airmass_ra, 1, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.hcalc_airmass)
        self.label_53.setObjectName("label_53")
        self.gridLayout_78.addWidget(self.label_53, 2, 0, 1, 1)
        self.hcalc_airmass_dec = QtWidgets.QComboBox(self.hcalc_airmass)
        self.hcalc_airmass_dec.setObjectName("hcalc_airmass_dec")
        self.gridLayout_78.addWidget(self.hcalc_airmass_dec, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.hcalc_airmass)
        self.label_60.setObjectName("label_60")
        self.gridLayout_78.addWidget(self.label_60, 3, 0, 1, 1)
        self.hcalc_airmass_observatory = QtWidgets.QComboBox(self.hcalc_airmass)
        self.hcalc_airmass_observatory.setObjectName("hcalc_airmass_observatory")
        self.gridLayout_78.addWidget(self.hcalc_airmass_observatory, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.hcalc_airmass, 1, 0, 1, 2)
        self.hcalc_imexamine = QtWidgets.QGroupBox(Form)
        self.hcalc_imexamine.setMaximumSize(QtCore.QSize(16777215, 66))
        self.hcalc_imexamine.setCheckable(True)
        self.hcalc_imexamine.setObjectName("hcalc_imexamine")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.hcalc_imexamine)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.hcalc_imexamine_mean = QtWidgets.QCheckBox(self.hcalc_imexamine)
        self.hcalc_imexamine_mean.setChecked(True)
        self.hcalc_imexamine_mean.setObjectName("hcalc_imexamine_mean")
        self.gridLayout_51.addWidget(self.hcalc_imexamine_mean, 0, 0, 1, 1)
        self.hcalc_imexamine_median = QtWidgets.QCheckBox(self.hcalc_imexamine)
        self.hcalc_imexamine_median.setChecked(True)
        self.hcalc_imexamine_median.setObjectName("hcalc_imexamine_median")
        self.gridLayout_51.addWidget(self.hcalc_imexamine_median, 0, 1, 1, 1)
        self.hcalc_imexamine_stdv = QtWidgets.QCheckBox(self.hcalc_imexamine)
        self.hcalc_imexamine_stdv.setChecked(True)
        self.hcalc_imexamine_stdv.setObjectName("hcalc_imexamine_stdv")
        self.gridLayout_51.addWidget(self.hcalc_imexamine_stdv, 0, 2, 1, 1)
        self.hcalc_imexamine_min = QtWidgets.QCheckBox(self.hcalc_imexamine)
        self.hcalc_imexamine_min.setChecked(True)
        self.hcalc_imexamine_min.setObjectName("hcalc_imexamine_min")
        self.gridLayout_51.addWidget(self.hcalc_imexamine_min, 0, 3, 1, 1)
        self.hcalc_imexamine_max = QtWidgets.QCheckBox(self.hcalc_imexamine)
        self.hcalc_imexamine_max.setChecked(True)
        self.hcalc_imexamine_max.setObjectName("hcalc_imexamine_max")
        self.gridLayout_51.addWidget(self.hcalc_imexamine_max, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.hcalc_imexamine, 2, 0, 1, 2)
        self.hcalc_time = QtWidgets.QGroupBox(Form)
        self.hcalc_time.setMaximumSize(QtCore.QSize(16777215, 114))
        self.hcalc_time.setCheckable(True)
        self.hcalc_time.setObjectName("hcalc_time")
        self.gridLayout_59 = QtWidgets.QGridLayout(self.hcalc_time)
        self.gridLayout_59.setObjectName("gridLayout_59")
        self.label_61 = QtWidgets.QLabel(self.hcalc_time)
        self.label_61.setObjectName("label_61")
        self.gridLayout_59.addWidget(self.label_61, 0, 0, 1, 2)
        self.hcalc_time_time = QtWidgets.QComboBox(self.hcalc_time)
        self.hcalc_time_time.setObjectName("hcalc_time_time")
        self.gridLayout_59.addWidget(self.hcalc_time_time, 0, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.hcalc_time)
        self.label_7.setObjectName("label_7")
        self.gridLayout_59.addWidget(self.label_7, 1, 0, 1, 1)
        self.hcalc_time_value = QtWidgets.QDoubleSpinBox(self.hcalc_time)
        self.hcalc_time_value.setDecimals(8)
        self.hcalc_time_value.setMinimum(-31536000.0)
        self.hcalc_time_value.setMaximum(31536000.0)
        self.hcalc_time_value.setSingleStep(0.001)
        self.hcalc_time_value.setProperty("value", 3.0)
        self.hcalc_time_value.setObjectName("hcalc_time_value")
        self.gridLayout_59.addWidget(self.hcalc_time_value, 1, 1, 1, 2)
        self.hcalc_time_valueType = QtWidgets.QComboBox(self.hcalc_time)
        self.hcalc_time_valueType.setObjectName("hcalc_time_valueType")
        self.hcalc_time_valueType.addItem("")
        self.hcalc_time_valueType.addItem("")
        self.hcalc_time_valueType.addItem("")
        self.gridLayout_59.addWidget(self.hcalc_time_valueType, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.hcalc_time, 3, 0, 1, 2)
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 4, 0, 1, 1)
        self.hcalc_prefix = QtWidgets.QLineEdit(Form)
        self.hcalc_prefix.setObjectName("hcalc_prefix")
        self.gridLayout.addWidget(self.hcalc_prefix, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.gridLayout_76 = QtWidgets.QGridLayout()
        self.gridLayout_76.setObjectName("gridLayout_76")
        self.hcalc_annotation = QtWidgets.QLabel(Form)
        self.hcalc_annotation.setText("")
        self.hcalc_annotation.setObjectName("hcalc_annotation")
        self.gridLayout_76.addWidget(self.hcalc_annotation, 0, 0, 1, 1)
        self.hcalc_go = QtWidgets.QPushButton(Form)
        self.hcalc_go.setMinimumSize(QtCore.QSize(50, 50))
        self.hcalc_go.setMaximumSize(QtCore.QSize(50, 50))
        self.hcalc_go.setObjectName("hcalc_go")
        self.gridLayout_76.addWidget(self.hcalc_go, 0, 1, 2, 1)
        self.hcalc_progress = QtWidgets.QProgressBar(Form)
        self.hcalc_progress.setProperty("value", 24)
        self.hcalc_progress.setObjectName("hcalc_progress")
        self.gridLayout_76.addWidget(self.hcalc_progress, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_76, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Header Calculator"))
        self.hcalc_jd.setTitle(_translate("Form", "&JD Calculator"))
        self.label_51.setText(_translate("Form", "Time In Header"))
        self.hcalc_airmass.setTitle(_translate("Form", "Airmass Calculator"))
        self.label_59.setText(_translate("Form", "Time In Header"))
        self.label_52.setText(_translate("Form", "RA In Header"))
        self.label_53.setText(_translate("Form", "DEC In Header"))
        self.label_60.setText(_translate("Form", "Observatory"))
        self.hcalc_imexamine.setTitle(_translate("Form", "Ime&xamine"))
        self.hcalc_imexamine_mean.setText(_translate("Form", "Mean"))
        self.hcalc_imexamine_median.setText(_translate("Form", "Median"))
        self.hcalc_imexamine_stdv.setText(_translate("Form", "STDV"))
        self.hcalc_imexamine_min.setText(_translate("Form", "Min"))
        self.hcalc_imexamine_max.setText(_translate("Form", "Max"))
        self.hcalc_time.setTitle(_translate("Form", "Time Calculator"))
        self.label_61.setText(_translate("Form", "Time In Header"))
        self.label_7.setText(_translate("Form", "Time Offset"))
        self.hcalc_time_valueType.setItemText(0, _translate("Form", "Hours"))
        self.hcalc_time_valueType.setItemText(1, _translate("Form", "Minutes"))
        self.hcalc_time_valueType.setItemText(2, _translate("Form", "Seconds"))
        self.label_50.setText(_translate("Form", "Prefix"))
        self.hcalc_prefix.setText(_translate("Form", "my"))
        self.hcalc_go.setText(_translate("Form", ":go"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
