# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myraf.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 765)
        MainWindow.setMinimumSize(QtCore.QSize(776, 587))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/myraf/64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.play_ground = QtWidgets.QMdiArea(self.centralwidget)
        self.play_ground.setAutoFillBackground(False)
        brush = QtGui.QBrush(QtGui.QColor(136, 142, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.play_ground.setBackground(brush)
        self.play_ground.setObjectName("play_ground")
        self.gridLayout_6.addWidget(self.play_ground, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuData = QtWidgets.QMenu(self.menuFile)
        self.menuData.setObjectName("menuData")
        self.menuClear_Lists = QtWidgets.QMenu(self.menuFile)
        self.menuClear_Lists.setObjectName("menuClear_Lists")
        self.menuAnalyse = QtWidgets.QMenu(self.menubar)
        self.menuAnalyse.setObjectName("menuAnalyse")
        self.menuCombine = QtWidgets.QMenu(self.menuAnalyse)
        self.menuCombine.setObjectName("menuCombine")
        self.menuIRAF_Combine = QtWidgets.QMenu(self.menuCombine)
        self.menuIRAF_Combine.setObjectName("menuIRAF_Combine")
        self.menuAlign = QtWidgets.QMenu(self.menuAnalyse)
        self.menuAlign.setObjectName("menuAlign")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHeader = QtWidgets.QMenu(self.menuEdit)
        self.menuHeader.setObjectName("menuHeader")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menuHelp)
        self.menuHelp_2.setObjectName("menuHelp_2")
        self.menuMYRaf = QtWidgets.QMenu(self.menuHelp_2)
        self.menuMYRaf.setObjectName("menuMYRaf")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.file_containter = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.file_containter.setObjectName("file_containter")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image_list = QtWidgets.QTreeWidget(self.tab)
        self.image_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.image_list.setObjectName("image_list")
        self.gridLayout_2.addWidget(self.image_list, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.image_remove = QtWidgets.QPushButton(self.tab)
        self.image_remove.setObjectName("image_remove")
        self.gridLayout_2.addWidget(self.image_remove, 1, 1, 1, 1)
        self.image_add = QtWidgets.QPushButton(self.tab)
        self.image_add.setObjectName("image_add")
        self.gridLayout_2.addWidget(self.image_add, 1, 2, 1, 1)
        self.file_containter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bias_list = QtWidgets.QTreeWidget(self.tab_2)
        self.bias_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.bias_list.setObjectName("bias_list")
        self.gridLayout_3.addWidget(self.bias_list, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.bias_remove = QtWidgets.QPushButton(self.tab_2)
        self.bias_remove.setObjectName("bias_remove")
        self.gridLayout_3.addWidget(self.bias_remove, 1, 1, 1, 1)
        self.bias_add = QtWidgets.QPushButton(self.tab_2)
        self.bias_add.setObjectName("bias_add")
        self.gridLayout_3.addWidget(self.bias_add, 1, 2, 1, 1)
        self.file_containter.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dark_list = QtWidgets.QTreeWidget(self.tab_3)
        self.dark_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dark_list.setObjectName("dark_list")
        self.gridLayout_4.addWidget(self.dark_list, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.dark_remove = QtWidgets.QPushButton(self.tab_3)
        self.dark_remove.setObjectName("dark_remove")
        self.gridLayout_4.addWidget(self.dark_remove, 1, 1, 1, 1)
        self.dark_add = QtWidgets.QPushButton(self.tab_3)
        self.dark_add.setObjectName("dark_add")
        self.gridLayout_4.addWidget(self.dark_add, 1, 2, 1, 1)
        self.file_containter.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.flat_list = QtWidgets.QTreeWidget(self.tab_4)
        self.flat_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.flat_list.setObjectName("flat_list")
        self.gridLayout_5.addWidget(self.flat_list, 0, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.flat_remove = QtWidgets.QPushButton(self.tab_4)
        self.flat_remove.setObjectName("flat_remove")
        self.gridLayout_5.addWidget(self.flat_remove, 1, 1, 1, 1)
        self.flat_add = QtWidgets.QPushButton(self.tab_4)
        self.flat_add.setObjectName("flat_add")
        self.gridLayout_5.addWidget(self.flat_add, 1, 2, 1, 1)
        self.file_containter.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.file_containter, 0, 0, 1, 1)
        self.annotation = QtWidgets.QLabel(self.dockWidgetContents)
        self.annotation.setText("")
        self.annotation.setObjectName("annotation")
        self.gridLayout.addWidget(self.annotation, 1, 0, 1, 1)
        self.progress = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.gridLayout.addWidget(self.progress, 2, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCalibration = QtWidgets.QAction(MainWindow)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionPhotometry = QtWidgets.QAction(MainWindow)
        self.actionPhotometry.setObjectName("actionPhotometry")
        self.actionA_Track = QtWidgets.QAction(MainWindow)
        self.actionA_Track.setObjectName("actionA_Track")
        self.actionObservatory = QtWidgets.QAction(MainWindow)
        self.actionObservatory.setObjectName("actionObservatory")
        self.actionCosmic = QtWidgets.QAction(MainWindow)
        self.actionCosmic.setObjectName("actionCosmic")
        self.actionWCS = QtWidgets.QAction(MainWindow)
        self.actionWCS.setObjectName("actionWCS")
        self.actionHedit = QtWidgets.QAction(MainWindow)
        self.actionHedit.setObjectName("actionHedit")
        self.actionHeader_Calculator = QtWidgets.QAction(MainWindow)
        self.actionHeader_Calculator.setObjectName("actionHeader_Calculator")
        self.actionHeader_Extractor = QtWidgets.QAction(MainWindow)
        self.actionHeader_Extractor.setObjectName("actionHeader_Extractor")
        self.actionCalibration_2 = QtWidgets.QAction(MainWindow)
        self.actionCalibration_2.setObjectName("actionCalibration_2")
        self.actionPhotometry_2 = QtWidgets.QAction(MainWindow)
        self.actionPhotometry_2.setObjectName("actionPhotometry_2")
        self.actionCosmic_Cleaner = QtWidgets.QAction(MainWindow)
        self.actionCosmic_Cleaner.setObjectName("actionCosmic_Cleaner")
        self.actionWCS_2 = QtWidgets.QAction(MainWindow)
        self.actionWCS_2.setObjectName("actionWCS_2")
        self.actionAbout_MYRaf = QtWidgets.QAction(MainWindow)
        self.actionAbout_MYRaf.setObjectName("actionAbout_MYRaf")
        self.actionGinga = QtWidgets.QAction(MainWindow)
        self.actionGinga.setObjectName("actionGinga")
        self.actionAlipy = QtWidgets.QAction(MainWindow)
        self.actionAlipy.setObjectName("actionAlipy")
        self.actionLA_Cosmic_Cleaner = QtWidgets.QAction(MainWindow)
        self.actionLA_Cosmic_Cleaner.setObjectName("actionLA_Cosmic_Cleaner")
        self.actionAstrometry_net = QtWidgets.QAction(MainWindow)
        self.actionAstrometry_net.setObjectName("actionAstrometry_net")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionLog_Viewer = QtWidgets.QAction(MainWindow)
        self.actionLog_Viewer.setObjectName("actionLog_Viewer")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionBias = QtWidgets.QAction(MainWindow)
        self.actionBias.setObjectName("actionBias")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionFlat = QtWidgets.QAction(MainWindow)
        self.actionFlat.setObjectName("actionFlat")
        self.actionAddImage = QtWidgets.QAction(MainWindow)
        self.actionAddImage.setObjectName("actionAddImage")
        self.actionAddBias = QtWidgets.QAction(MainWindow)
        self.actionAddBias.setObjectName("actionAddBias")
        self.actionAddDark = QtWidgets.QAction(MainWindow)
        self.actionAddDark.setObjectName("actionAddDark")
        self.actionAddFlat = QtWidgets.QAction(MainWindow)
        self.actionAddFlat.setObjectName("actionAddFlat")
        self.actionBias_Combine = QtWidgets.QAction(MainWindow)
        self.actionBias_Combine.setObjectName("actionBias_Combine")
        self.actionDark_Combine = QtWidgets.QAction(MainWindow)
        self.actionDark_Combine.setObjectName("actionDark_Combine")
        self.actionFlat_Combine = QtWidgets.QAction(MainWindow)
        self.actionFlat_Combine.setObjectName("actionFlat_Combine")
        self.actionMedian = QtWidgets.QAction(MainWindow)
        self.actionMedian.setObjectName("actionMedian")
        self.actionAverage = QtWidgets.QAction(MainWindow)
        self.actionAverage.setObjectName("actionAverage")
        self.actionSum = QtWidgets.QAction(MainWindow)
        self.actionSum.setObjectName("actionSum")
        self.actionDifference = QtWidgets.QAction(MainWindow)
        self.actionDifference.setObjectName("actionDifference")
        self.actionGinga_2 = QtWidgets.QAction(MainWindow)
        self.actionGinga_2.setObjectName("actionGinga_2")
        self.actionAlipy_2 = QtWidgets.QAction(MainWindow)
        self.actionAlipy_2.setObjectName("actionAlipy_2")
        self.actionLA_Cosmic_Cleaner_2 = QtWidgets.QAction(MainWindow)
        self.actionLA_Cosmic_Cleaner_2.setObjectName("actionLA_Cosmic_Cleaner_2")
        self.actionAstrometry_net_2 = QtWidgets.QAction(MainWindow)
        self.actionAstrometry_net_2.setObjectName("actionAstrometry_net_2")
        self.actionEditor = QtWidgets.QAction(MainWindow)
        self.actionEditor.setObjectName("actionEditor")
        self.actionCombine = QtWidgets.QAction(MainWindow)
        self.actionCombine.setObjectName("actionCombine")
        self.actionCalibration_3 = QtWidgets.QAction(MainWindow)
        self.actionCalibration_3.setObjectName("actionCalibration_3")
        self.actionAnalyse_2 = QtWidgets.QAction(MainWindow)
        self.actionAnalyse_2.setObjectName("actionAnalyse_2")
        self.actionClose_All_Windows = QtWidgets.QAction(MainWindow)
        self.actionClose_All_Windows.setObjectName("actionClose_All_Windows")
        self.actionClear_All_Lists = QtWidgets.QAction(MainWindow)
        self.actionClear_All_Lists.setObjectName("actionClear_All_Lists")
        self.actionClear_Image_List = QtWidgets.QAction(MainWindow)
        self.actionClear_Image_List.setObjectName("actionClear_Image_List")
        self.actionClear_Bias_List = QtWidgets.QAction(MainWindow)
        self.actionClear_Bias_List.setObjectName("actionClear_Bias_List")
        self.actionClear_Dark_List = QtWidgets.QAction(MainWindow)
        self.actionClear_Dark_List.setObjectName("actionClear_Dark_List")
        self.actionClear_Flat_List = QtWidgets.QAction(MainWindow)
        self.actionClear_Flat_List.setObjectName("actionClear_Flat_List")
        self.actionClear_Image_L_st = QtWidgets.QAction(MainWindow)
        self.actionClear_Image_L_st.setObjectName("actionClear_Image_L_st")
        self.actionClear_Bias_List_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_Bias_List_2.setObjectName("actionClear_Bias_List_2")
        self.actionClear_Dark_L_st = QtWidgets.QAction(MainWindow)
        self.actionClear_Dark_L_st.setObjectName("actionClear_Dark_L_st")
        self.actionClear_Flat_List_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_Flat_List_2.setObjectName("actionClear_Flat_List_2")
        self.actionClear_Image_List_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_Image_List_2.setObjectName("actionClear_Image_List_2")
        self.actionClear_Image_List_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Image_List_3.setObjectName("actionClear_Image_List_3")
        self.actionClear_Bias_List_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Bias_List_3.setObjectName("actionClear_Bias_List_3")
        self.actionClear_Dark_List_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Dark_List_3.setObjectName("actionClear_Dark_List_3")
        self.actionClear_Flat_List_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Flat_List_3.setObjectName("actionClear_Flat_List_3")
        self.actionZerocombine = QtWidgets.QAction(MainWindow)
        self.actionZerocombine.setObjectName("actionZerocombine")
        self.actionDarlcombine = QtWidgets.QAction(MainWindow)
        self.actionDarlcombine.setObjectName("actionDarlcombine")
        self.actionFlatcombine = QtWidgets.QAction(MainWindow)
        self.actionFlatcombine.setObjectName("actionFlatcombine")
        self.actionDarkcombine = QtWidgets.QAction(MainWindow)
        self.actionDarkcombine.setObjectName("actionDarkcombine")
        self.actionManualAlign = QtWidgets.QAction(MainWindow)
        self.actionManualAlign.setObjectName("actionManualAlign")
        self.actionAutoAlign = QtWidgets.QAction(MainWindow)
        self.actionAutoAlign.setObjectName("actionAutoAlign")
        self.actionMain = QtWidgets.QAction(MainWindow)
        self.actionMain.setObjectName("actionMain")
        self.actionAlbatenius = QtWidgets.QAction(MainWindow)
        self.actionAlbatenius.setObjectName("actionAlbatenius")
        self.menuData.addAction(self.actionAddImage)
        self.menuData.addAction(self.actionAddBias)
        self.menuData.addAction(self.actionAddDark)
        self.menuData.addAction(self.actionAddFlat)
        self.menuClear_Lists.addAction(self.actionClear_All_Lists)
        self.menuClear_Lists.addAction(self.actionClear_Image_List_3)
        self.menuClear_Lists.addAction(self.actionClear_Bias_List_3)
        self.menuClear_Lists.addAction(self.actionClear_Dark_List_3)
        self.menuClear_Lists.addAction(self.actionClear_Flat_List_3)
        self.menuFile.addAction(self.menuData.menuAction())
        self.menuFile.addAction(self.menuClear_Lists.menuAction())
        self.menuFile.addAction(self.actionClose_All_Windows)
        self.menuFile.addAction(self.actionQuit)
        self.menuIRAF_Combine.addAction(self.actionZerocombine)
        self.menuIRAF_Combine.addAction(self.actionDarkcombine)
        self.menuIRAF_Combine.addAction(self.actionFlatcombine)
        self.menuCombine.addAction(self.menuIRAF_Combine.menuAction())
        self.menuCombine.addAction(self.actionMedian)
        self.menuCombine.addAction(self.actionAverage)
        self.menuCombine.addAction(self.actionSum)
        self.menuCombine.addAction(self.actionDifference)
        self.menuAlign.addAction(self.actionAutoAlign)
        self.menuAlign.addAction(self.actionManualAlign)
        self.menuAnalyse.addAction(self.menuCombine.menuAction())
        self.menuAnalyse.addAction(self.actionCalibration)
        self.menuAnalyse.addAction(self.menuAlign.menuAction())
        self.menuAnalyse.addAction(self.actionPhotometry)
        self.menuAnalyse.addAction(self.actionA_Track)
        self.menuHeader.addAction(self.actionHedit)
        self.menuHeader.addAction(self.actionHeader_Calculator)
        self.menuHeader.addAction(self.actionHeader_Extractor)
        self.menuEdit.addAction(self.menuHeader.menuAction())
        self.menuEdit.addAction(self.actionObservatory)
        self.menuEdit.addAction(self.actionCosmic)
        self.menuEdit.addAction(self.actionWCS)
        self.menuSettings.addAction(self.actionCalibration_2)
        self.menuSettings.addAction(self.actionPhotometry_2)
        self.menuSettings.addAction(self.actionCosmic_Cleaner)
        self.menuSettings.addAction(self.actionWCS_2)
        self.menuMYRaf.addAction(self.actionMain)
        self.menuMYRaf.addAction(self.actionAnalyse_2)
        self.menuMYRaf.addAction(self.actionEditor)
        self.menuHelp_2.addAction(self.menuMYRaf.menuAction())
        self.menuHelp_2.addAction(self.actionGinga_2)
        self.menuHelp_2.addAction(self.actionAlipy_2)
        self.menuHelp_2.addAction(self.actionLA_Cosmic_Cleaner_2)
        self.menuHelp_2.addAction(self.actionAstrometry_net_2)
        self.menuHelp.addAction(self.menuHelp_2.menuAction())
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionLog_Viewer)
        self.menuHelp.addAction(self.actionAbout_MYRaf)
        self.menuHelp.addAction(self.actionAlbatenius)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.file_containter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MYRaf (V3 - Beta) Albatenius"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuData.setTitle(_translate("MainWindow", "&Import Data"))
        self.menuClear_Lists.setTitle(_translate("MainWindow", "&Clear List"))
        self.menuAnalyse.setTitle(_translate("MainWindow", "A&nalyse"))
        self.menuCombine.setTitle(_translate("MainWindow", "&Combine"))
        self.menuIRAF_Combine.setTitle(_translate("MainWindow", "&IRAF Combine"))
        self.menuAlign.setTitle(_translate("MainWindow", "&Align"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&ditor"))
        self.menuHeader.setTitle(_translate("MainWindow", "&Header"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settin&gs"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "&Help"))
        self.menuMYRaf.setTitle(_translate("MainWindow", "&MYRaf"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Fi&les"))
        self.image_list.headerItem().setText(0, _translate("MainWindow", "Attribute"))
        self.image_list.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.image_remove.setText(_translate("MainWindow", "Remove"))
        self.image_add.setText(_translate("MainWindow", "Add"))
        self.file_containter.setTabText(self.file_containter.indexOf(self.tab), _translate("MainWindow", "Image"))
        self.bias_list.headerItem().setText(0, _translate("MainWindow", "Attribute"))
        self.bias_list.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.bias_remove.setText(_translate("MainWindow", "Remove"))
        self.bias_add.setText(_translate("MainWindow", "Add"))
        self.file_containter.setTabText(self.file_containter.indexOf(self.tab_2), _translate("MainWindow", "Bias"))
        self.dark_list.headerItem().setText(0, _translate("MainWindow", "Attribute"))
        self.dark_list.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.dark_remove.setText(_translate("MainWindow", "Remove"))
        self.dark_add.setText(_translate("MainWindow", "Add"))
        self.file_containter.setTabText(self.file_containter.indexOf(self.tab_3), _translate("MainWindow", "Dark"))
        self.flat_list.headerItem().setText(0, _translate("MainWindow", "Attribute"))
        self.flat_list.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.flat_remove.setText(_translate("MainWindow", "Remove"))
        self.flat_add.setText(_translate("MainWindow", "Add"))
        self.file_containter.setTabText(self.file_containter.indexOf(self.tab_4), _translate("MainWindow", "Flat"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionCalibration.setText(_translate("MainWindow", "Ca&libration"))
        self.actionPhotometry.setText(_translate("MainWindow", "&Photometry ..."))
        self.actionA_Track.setText(_translate("MainWindow", "A-T&rack"))
        self.actionObservatory.setText(_translate("MainWindow", "&Observatory ..."))
        self.actionCosmic.setText(_translate("MainWindow", "&Cosmic Cleaner"))
        self.actionWCS.setText(_translate("MainWindow", "&WCS"))
        self.actionHedit.setText(_translate("MainWindow", "&Hedit ..."))
        self.actionHeader_Calculator.setText(_translate("MainWindow", "Header &Calculator ..."))
        self.actionHeader_Extractor.setText(_translate("MainWindow", "Header &Extractor ..."))
        self.actionCalibration_2.setText(_translate("MainWindow", "&Calibration"))
        self.actionPhotometry_2.setText(_translate("MainWindow", "&Photometry"))
        self.actionCosmic_Cleaner.setText(_translate("MainWindow", "C&osmic Cleaner"))
        self.actionWCS_2.setText(_translate("MainWindow", "&WCS"))
        self.actionAbout_MYRaf.setText(_translate("MainWindow", "&About MYRaf ..."))
        self.actionGinga.setText(_translate("MainWindow", "Ginga"))
        self.actionAlipy.setText(_translate("MainWindow", "Alipy"))
        self.actionLA_Cosmic_Cleaner.setText(_translate("MainWindow", "LA. Cosmic Cleaner"))
        self.actionAstrometry_net.setText(_translate("MainWindow", "Astrometry.net"))
        self.actionLicense.setText(_translate("MainWindow", "&License ..."))
        self.actionCredits.setText(_translate("MainWindow", "&Credits ..."))
        self.actionLog_Viewer.setText(_translate("MainWindow", "Log &Viewer ..."))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionBias.setText(_translate("MainWindow", "Bias"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionFlat.setText(_translate("MainWindow", "Flat"))
        self.actionAddImage.setText(_translate("MainWindow", "&Image"))
        self.actionAddBias.setText(_translate("MainWindow", "&Bias"))
        self.actionAddDark.setText(_translate("MainWindow", "&Dark"))
        self.actionAddFlat.setText(_translate("MainWindow", "&Flat"))
        self.actionBias_Combine.setText(_translate("MainWindow", "Bias Combine"))
        self.actionDark_Combine.setText(_translate("MainWindow", "Dark Combine"))
        self.actionFlat_Combine.setText(_translate("MainWindow", "Flat Combine"))
        self.actionMedian.setText(_translate("MainWindow", "&Median..."))
        self.actionAverage.setText(_translate("MainWindow", "&Average..."))
        self.actionSum.setText(_translate("MainWindow", "&Sum..."))
        self.actionDifference.setText(_translate("MainWindow", "&Difference ..."))
        self.actionGinga_2.setText(_translate("MainWindow", "&Ginga ..."))
        self.actionAlipy_2.setText(_translate("MainWindow", "&Alipy ..."))
        self.actionLA_Cosmic_Cleaner_2.setText(_translate("MainWindow", "&LA. Cosmic Cleaner ..."))
        self.actionAstrometry_net_2.setText(_translate("MainWindow", "Astrometry.&net ..."))
        self.actionEditor.setText(_translate("MainWindow", "&Editor"))
        self.actionCombine.setText(_translate("MainWindow", "Combine"))
        self.actionCalibration_3.setText(_translate("MainWindow", "Calibration"))
        self.actionAnalyse_2.setText(_translate("MainWindow", "&Analyse"))
        self.actionClose_All_Windows.setText(_translate("MainWindow", "Close All &Open Windows"))
        self.actionClear_All_Lists.setText(_translate("MainWindow", "&Clear All Lists"))
        self.actionClear_Image_List.setText(_translate("MainWindow", "Clear Image List"))
        self.actionClear_Bias_List.setText(_translate("MainWindow", "Clear Bias List"))
        self.actionClear_Dark_List.setText(_translate("MainWindow", "Clear Dark List"))
        self.actionClear_Flat_List.setText(_translate("MainWindow", "Clear Flat List"))
        self.actionClear_Image_L_st.setText(_translate("MainWindow", "Clear Image Lİst"))
        self.actionClear_Bias_List_2.setText(_translate("MainWindow", "Clear Bias List"))
        self.actionClear_Dark_L_st.setText(_translate("MainWindow", "Clear Dark Lİst"))
        self.actionClear_Flat_List_2.setText(_translate("MainWindow", "Clear Flat List"))
        self.actionClear_Image_List_2.setText(_translate("MainWindow", "Clear Image List"))
        self.actionClear_Image_List_3.setText(_translate("MainWindow", "Clear &Image List"))
        self.actionClear_Bias_List_3.setText(_translate("MainWindow", "Clear &Bias List"))
        self.actionClear_Dark_List_3.setText(_translate("MainWindow", "Clear &Dark List"))
        self.actionClear_Flat_List_3.setText(_translate("MainWindow", "Clear &Flat List"))
        self.actionZerocombine.setText(_translate("MainWindow", "&Zerocombine..."))
        self.actionDarlcombine.setText(_translate("MainWindow", "Darlcombine"))
        self.actionFlatcombine.setText(_translate("MainWindow", "&Flatcombine..."))
        self.actionDarkcombine.setText(_translate("MainWindow", "&Darkcombine..."))
        self.actionManualAlign.setText(_translate("MainWindow", "&Manual..."))
        self.actionAutoAlign.setText(_translate("MainWindow", "&Auto"))
        self.actionMain.setText(_translate("MainWindow", "&Main"))
        self.actionAlbatenius.setText(_translate("MainWindow", "Al&batenius ..."))


#import myraf_sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
