# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'observatory.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 468)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_12 = QtWidgets.QGroupBox(Form)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setObjectName("label_20")
        self.gridLayout_46.addWidget(self.label_20, 0, 0, 1, 1)
        self.observatory_abbreviation = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_abbreviation.setObjectName("observatory_abbreviation")
        self.gridLayout_46.addWidget(self.observatory_abbreviation, 0, 1, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.groupBox_12)
        self.label_21.setObjectName("label_21")
        self.gridLayout_46.addWidget(self.label_21, 1, 0, 1, 1)
        self.observatory_name = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_name.setObjectName("observatory_name")
        self.gridLayout_46.addWidget(self.observatory_name, 1, 1, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setObjectName("label_22")
        self.gridLayout_46.addWidget(self.label_22, 2, 0, 1, 1)
        self.observatory_longitude = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_longitude.setObjectName("observatory_longitude")
        self.gridLayout_46.addWidget(self.observatory_longitude, 2, 1, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_46.addWidget(self.label_23, 3, 0, 1, 1)
        self.observatory_latitude = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_latitude.setObjectName("observatory_latitude")
        self.gridLayout_46.addWidget(self.observatory_latitude, 3, 1, 1, 3)
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setObjectName("label_24")
        self.gridLayout_46.addWidget(self.label_24, 4, 0, 1, 1)
        self.observatory_altitude = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_altitude.setObjectName("observatory_altitude")
        self.gridLayout_46.addWidget(self.observatory_altitude, 4, 1, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        self.label_26.setObjectName("label_26")
        self.gridLayout_46.addWidget(self.label_26, 5, 0, 1, 1)
        self.observatory_timezone = QtWidgets.QLineEdit(self.groupBox_12)
        self.observatory_timezone.setObjectName("observatory_timezone")
        self.gridLayout_46.addWidget(self.observatory_timezone, 5, 1, 1, 3)
        self.label_25 = QtWidgets.QLabel(self.groupBox_12)
        self.label_25.setObjectName("label_25")
        self.gridLayout_46.addWidget(self.label_25, 6, 0, 1, 1)
        self.observatory_commend = QtWidgets.QPlainTextEdit(self.groupBox_12)
        self.observatory_commend.setObjectName("observatory_commend")
        self.gridLayout_46.addWidget(self.observatory_commend, 7, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(377, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_46.addItem(spacerItem, 8, 0, 1, 2)
        self.observatory_remove = QtWidgets.QPushButton(self.groupBox_12)
        self.observatory_remove.setMinimumSize(QtCore.QSize(72, 0))
        self.observatory_remove.setMaximumSize(QtCore.QSize(72, 16777215))
        self.observatory_remove.setObjectName("observatory_remove")
        self.gridLayout_46.addWidget(self.observatory_remove, 8, 2, 1, 1)
        self.observatory_add = QtWidgets.QPushButton(self.groupBox_12)
        self.observatory_add.setMinimumSize(QtCore.QSize(72, 0))
        self.observatory_add.setMaximumSize(QtCore.QSize(72, 16777215))
        self.observatory_add.setObjectName("observatory_add")
        self.gridLayout_46.addWidget(self.observatory_add, 8, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        self.groupBox_11.setMinimumSize(QtCore.QSize(170, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(170, 16777215))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.observatory_list = QtWidgets.QListWidget(self.groupBox_11)
        self.observatory_list.setMinimumSize(QtCore.QSize(150, 0))
        self.observatory_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.observatory_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.observatory_list.setObjectName("observatory_list")
        self.gridLayout_36.addWidget(self.observatory_list, 0, 0, 1, 1)
        self.observatory_reload = QtWidgets.QPushButton(self.groupBox_11)
        self.observatory_reload.setObjectName("observatory_reload")
        self.gridLayout_36.addWidget(self.observatory_reload, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_11, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Observatory"))
        self.groupBox_12.setTitle(_translate("Form", "Properties"))
        self.label_20.setText(_translate("Form", "Observatory"))
        self.label_21.setText(_translate("Form", "Name"))
        self.label_22.setText(_translate("Form", "Longitude"))
        self.label_23.setText(_translate("Form", "Latitude"))
        self.label_24.setText(_translate("Form", "Altitude"))
        self.label_26.setText(_translate("Form", "Time Zone"))
        self.label_25.setText(_translate("Form", "Commendation"))
        self.observatory_remove.setText(_translate("Form", "Remove"))
        self.observatory_add.setText(_translate("Form", "Add"))
        self.groupBox_11.setTitle(_translate("Form", "Observatory List"))
        self.observatory_reload.setText(_translate("Form", "Reload"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
