#!/bin/bash
pyuic5 -x	align_manual.ui	-o	align_manual.py
pyuic5 -x	animate.ui	-o	animate.py
pyuic5 -x	combine_subtraction.ui	-o	combine_subtraction.py
pyuic5 -x	display.ui	-o	display.py
pyuic5 -x	header_calculator.ui	-o	header_calculator.py
pyuic5 -x	header_editor.ui	-o	header_editor.py
pyuic5 -x	header_extractor.ui	-o	header_extractor.py
pyuic5 -x	help_aboutmyraf.ui	-o	help_aboutmyraf.py
pyuic5 -x	help_analyse.ui	-o	help_analyse.py
pyuic5 -x	help_credits.ui	-o	help_credits.py
pyuic5 -x	help_editor.ui	-o	help_editor.py
pyuic5 -x	help_help_alipy.ui	-o	help_help_alipy.py
pyuic5 -x	help_help_astrometrynet.ui	-o	help_help_astrometrynet.py
pyuic5 -x	help_help_ccleaner.ui	-o	help_help_ccleaner.py
pyuic5 -x	help_help_ginga.ui	-o	help_help_ginga.py
pyuic5 -x	help_licence.ui	-o	help_licence.py
pyuic5 -x	help_logger.ui	-o	help_logger.py
pyuic5 -x	myraf_progress.ui	-o	myraf_progress.py
pyuic5 -x	myraf.ui	-o	myraf.py
pyuic5 -x	observatory.ui	-o	observatory.py
pyuic5 -x	photometry.ui	-o	photometry.py
pyuic5 -x	setting_astrometrynet.ui	-o	setting_astrometrynet.py
pyuic5 -x	setting_calibration.ui	-o	setting_calibration.py
pyuic5 -x	setting_cosmiccleaner.ui	-o	setting_cosmiccleaner.py
pyuic5 -x	setting_photometry.ui	-o	setting_photometry.py
pyuic5 -x	help_myraf.ui	-o	help_myraf.py
#pyuic5 -x	albategnius.ui	-o	albategnius.py
#pyrcc5 -o myraf_sources.py myraf_sources.qrc
