# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 447)
        Form.setMinimumSize(QtCore.QSize(253, 357))
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_21 = QtWidgets.QGroupBox(Form)
        self.groupBox_21.setMaximumSize(QtCore.QSize(16777215, 114))
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_54 = QtWidgets.QGridLayout()
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.setting_calibration_z_combine = QtWidgets.QComboBox(self.groupBox_21)
        self.setting_calibration_z_combine.setObjectName("setting_calibration_z_combine")
        self.setting_calibration_z_combine.addItem("")
        self.setting_calibration_z_combine.addItem("")
        self.gridLayout_54.addWidget(self.setting_calibration_z_combine, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_21)
        self.label_18.setObjectName("label_18")
        self.gridLayout_54.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_21)
        self.label_13.setObjectName("label_13")
        self.gridLayout_54.addWidget(self.label_13, 0, 0, 1, 1)
        self.setting_calibration_z_rejection = QtWidgets.QComboBox(self.groupBox_21)
        self.setting_calibration_z_rejection.setObjectName("setting_calibration_z_rejection")
        self.setting_calibration_z_rejection.addItem("")
        self.setting_calibration_z_rejection.addItem("")
        self.gridLayout_54.addWidget(self.setting_calibration_z_rejection, 1, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_54, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_21, 0, 0, 1, 2)
        self.groupBox_22 = QtWidgets.QGroupBox(Form)
        self.groupBox_22.setMaximumSize(QtCore.QSize(16777215, 149))
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.gridLayout_56 = QtWidgets.QGridLayout()
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.label_35 = QtWidgets.QLabel(self.groupBox_22)
        self.label_35.setObjectName("label_35")
        self.gridLayout_56.addWidget(self.label_35, 2, 0, 1, 1)
        self.setting_calibration_d_scale = QtWidgets.QComboBox(self.groupBox_22)
        self.setting_calibration_d_scale.setObjectName("setting_calibration_d_scale")
        self.setting_calibration_d_scale.addItem("")
        self.setting_calibration_d_scale.addItem("")
        self.gridLayout_56.addWidget(self.setting_calibration_d_scale, 2, 1, 1, 1)
        self.setting_calibration_d_combine = QtWidgets.QComboBox(self.groupBox_22)
        self.setting_calibration_d_combine.setObjectName("setting_calibration_d_combine")
        self.setting_calibration_d_combine.addItem("")
        self.setting_calibration_d_combine.addItem("")
        self.gridLayout_56.addWidget(self.setting_calibration_d_combine, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_22)
        self.label_29.setObjectName("label_29")
        self.gridLayout_56.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_22)
        self.label_30.setObjectName("label_30")
        self.gridLayout_56.addWidget(self.label_30, 1, 0, 1, 1)
        self.setting_calibration_d_rejection = QtWidgets.QComboBox(self.groupBox_22)
        self.setting_calibration_d_rejection.setObjectName("setting_calibration_d_rejection")
        self.setting_calibration_d_rejection.addItem("")
        self.setting_calibration_d_rejection.addItem("")
        self.gridLayout_56.addWidget(self.setting_calibration_d_rejection, 1, 1, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_56, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_22, 1, 0, 1, 2)
        self.groupBox_23 = QtWidgets.QGroupBox(Form)
        self.groupBox_23.setMaximumSize(QtCore.QSize(16777215, 114))
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_32 = QtWidgets.QLabel(self.groupBox_23)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 0, 0, 1, 1)
        self.setting_calibration_f_combine = QtWidgets.QComboBox(self.groupBox_23)
        self.setting_calibration_f_combine.setObjectName("setting_calibration_f_combine")
        self.setting_calibration_f_combine.addItem("")
        self.setting_calibration_f_combine.addItem("")
        self.gridLayout.addWidget(self.setting_calibration_f_combine, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_23)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 0, 1, 1)
        self.setting_calibration_f_rejection = QtWidgets.QComboBox(self.groupBox_23)
        self.setting_calibration_f_rejection.setObjectName("setting_calibration_f_rejection")
        self.setting_calibration_f_rejection.addItem("")
        self.setting_calibration_f_rejection.addItem("")
        self.gridLayout.addWidget(self.setting_calibration_f_rejection, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_23, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)
        self.setting_calibration_save = QtWidgets.QPushButton(Form)
        self.setting_calibration_save.setMinimumSize(QtCore.QSize(72, 0))
        self.setting_calibration_save.setMaximumSize(QtCore.QSize(72, 16777215))
        self.setting_calibration_save.setObjectName("setting_calibration_save")
        self.gridLayout_3.addWidget(self.setting_calibration_save, 4, 1, 1, 1)

        self.retranslateUi(Form)
        self.setting_calibration_z_rejection.setCurrentIndex(0)
        self.setting_calibration_d_scale.setCurrentIndex(1)
        self.setting_calibration_d_rejection.setCurrentIndex(0)
        self.setting_calibration_f_rejection.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calibration Settings"))
        self.groupBox_21.setTitle(_translate("Form", "Zero Combine Setting"))
        self.setting_calibration_z_combine.setItemText(0, _translate("Form", "median"))
        self.setting_calibration_z_combine.setItemText(1, _translate("Form", "average"))
        self.label_18.setText(_translate("Form", "Reject"))
        self.label_13.setText(_translate("Form", "Combine"))
        self.setting_calibration_z_rejection.setItemText(0, _translate("Form", "none"))
        self.setting_calibration_z_rejection.setItemText(1, _translate("Form", "minmax"))
        self.groupBox_22.setTitle(_translate("Form", "Dark Combine Setting"))
        self.label_35.setText(_translate("Form", "Scale"))
        self.setting_calibration_d_scale.setItemText(0, _translate("Form", "none"))
        self.setting_calibration_d_scale.setItemText(1, _translate("Form", "exposure"))
        self.setting_calibration_d_combine.setItemText(0, _translate("Form", "median"))
        self.setting_calibration_d_combine.setItemText(1, _translate("Form", "average"))
        self.label_29.setText(_translate("Form", "Combine"))
        self.label_30.setText(_translate("Form", "Reject"))
        self.setting_calibration_d_rejection.setItemText(0, _translate("Form", "none"))
        self.setting_calibration_d_rejection.setItemText(1, _translate("Form", "minmax"))
        self.groupBox_23.setTitle(_translate("Form", "Flat Combine Setting"))
        self.label_32.setText(_translate("Form", "Combine"))
        self.setting_calibration_f_combine.setItemText(0, _translate("Form", "median"))
        self.setting_calibration_f_combine.setItemText(1, _translate("Form", "average"))
        self.label_33.setText(_translate("Form", "Reject"))
        self.setting_calibration_f_rejection.setItemText(0, _translate("Form", "none"))
        self.setting_calibration_f_rejection.setItemText(1, _translate("Form", "minmax"))
        self.setting_calibration_save.setText(_translate("Form", "Save"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
