# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\msh\OneDrive\Belgeler\the_myraf\gui\setting_cosmiccleaner.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 226)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_84 = QtWidgets.QLabel(Form)
        self.label_84.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_84.setObjectName("label_84")
        self.gridLayout.addWidget(self.label_84, 0, 0, 1, 1)
        self.setting_cclener_gain = QtWidgets.QDoubleSpinBox(Form)
        self.setting_cclener_gain.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_gain.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_gain.setDecimals(7)
        self.setting_cclener_gain.setMaximum(100000000.0)
        self.setting_cclener_gain.setSingleStep(0.1)
        self.setting_cclener_gain.setProperty("value", 2.2)
        self.setting_cclener_gain.setObjectName("setting_cclener_gain")
        self.gridLayout.addWidget(self.setting_cclener_gain, 0, 1, 1, 2)
        self.label_85 = QtWidgets.QLabel(Form)
        self.label_85.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_85.setObjectName("label_85")
        self.gridLayout.addWidget(self.label_85, 1, 0, 1, 1)
        self.setting_cclener_readnoise = QtWidgets.QDoubleSpinBox(Form)
        self.setting_cclener_readnoise.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_readnoise.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_readnoise.setDecimals(7)
        self.setting_cclener_readnoise.setMaximum(100000000.0)
        self.setting_cclener_readnoise.setSingleStep(0.1)
        self.setting_cclener_readnoise.setProperty("value", 10.0)
        self.setting_cclener_readnoise.setObjectName("setting_cclener_readnoise")
        self.gridLayout.addWidget(self.setting_cclener_readnoise, 1, 1, 1, 2)
        self.label_86 = QtWidgets.QLabel(Form)
        self.label_86.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_86.setObjectName("label_86")
        self.gridLayout.addWidget(self.label_86, 2, 0, 1, 1)
        self.setting_cclener_sigmaclip = QtWidgets.QDoubleSpinBox(Form)
        self.setting_cclener_sigmaclip.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_sigmaclip.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_sigmaclip.setDecimals(7)
        self.setting_cclener_sigmaclip.setMaximum(100000000.0)
        self.setting_cclener_sigmaclip.setSingleStep(0.1)
        self.setting_cclener_sigmaclip.setProperty("value", 5.0)
        self.setting_cclener_sigmaclip.setObjectName("setting_cclener_sigmaclip")
        self.gridLayout.addWidget(self.setting_cclener_sigmaclip, 2, 1, 1, 2)
        self.label_87 = QtWidgets.QLabel(Form)
        self.label_87.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_87.setObjectName("label_87")
        self.gridLayout.addWidget(self.label_87, 3, 0, 1, 1)
        self.setting_cclener_sigmafraction = QtWidgets.QDoubleSpinBox(Form)
        self.setting_cclener_sigmafraction.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_sigmafraction.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_sigmafraction.setDecimals(7)
        self.setting_cclener_sigmafraction.setMaximum(100000000.0)
        self.setting_cclener_sigmafraction.setSingleStep(0.1)
        self.setting_cclener_sigmafraction.setProperty("value", 0.3)
        self.setting_cclener_sigmafraction.setObjectName("setting_cclener_sigmafraction")
        self.gridLayout.addWidget(self.setting_cclener_sigmafraction, 3, 1, 1, 2)
        self.label_88 = QtWidgets.QLabel(Form)
        self.label_88.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_88.setObjectName("label_88")
        self.gridLayout.addWidget(self.label_88, 4, 0, 1, 1)
        self.setting_cclener_objectlimit = QtWidgets.QDoubleSpinBox(Form)
        self.setting_cclener_objectlimit.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_objectlimit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_objectlimit.setDecimals(7)
        self.setting_cclener_objectlimit.setMaximum(100000000.0)
        self.setting_cclener_objectlimit.setSingleStep(0.1)
        self.setting_cclener_objectlimit.setProperty("value", 5.0)
        self.setting_cclener_objectlimit.setObjectName("setting_cclener_objectlimit")
        self.gridLayout.addWidget(self.setting_cclener_objectlimit, 4, 1, 1, 2)
        self.label_89 = QtWidgets.QLabel(Form)
        self.label_89.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_89.setObjectName("label_89")
        self.gridLayout.addWidget(self.label_89, 5, 0, 1, 1)
        self.setting_cclener_maxiteration = QtWidgets.QSpinBox(Form)
        self.setting_cclener_maxiteration.setMinimumSize(QtCore.QSize(194, 20))
        self.setting_cclener_maxiteration.setMaximumSize(QtCore.QSize(16777215, 20))
        self.setting_cclener_maxiteration.setMinimum(2)
        self.setting_cclener_maxiteration.setProperty("value", 4)
        self.setting_cclener_maxiteration.setObjectName("setting_cclener_maxiteration")
        self.gridLayout.addWidget(self.setting_cclener_maxiteration, 5, 1, 1, 2)
        self.setting_cclener_createmask = QtWidgets.QCheckBox(Form)
        self.setting_cclener_createmask.setMinimumSize(QtCore.QSize(265, 17))
        self.setting_cclener_createmask.setMaximumSize(QtCore.QSize(16777215, 17))
        self.setting_cclener_createmask.setObjectName("setting_cclener_createmask")
        self.gridLayout.addWidget(self.setting_cclener_createmask, 6, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(184, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 2)
        self.setting_cclener_save = QtWidgets.QPushButton(Form)
        self.setting_cclener_save.setMinimumSize(QtCore.QSize(72, 0))
        self.setting_cclener_save.setMaximumSize(QtCore.QSize(72, 16777215))
        self.setting_cclener_save.setObjectName("setting_cclener_save")
        self.gridLayout.addWidget(self.setting_cclener_save, 8, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cosmic Cleaner Settings"))
        self.label_84.setText(_translate("Form", "Gain"))
        self.label_85.setText(_translate("Form", "Read Noise"))
        self.label_86.setText(_translate("Form", "Sigma Clip"))
        self.label_87.setText(_translate("Form", "Sigma Frac."))
        self.label_88.setText(_translate("Form", "Object Lim."))
        self.label_89.setText(_translate("Form", "Max Iteration"))
        self.setting_cclener_createmask.setText(_translate("Form", "Save Mask files"))
        self.setting_cclener_save.setText(_translate("Form", "Save"))

