# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_photometry.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 502)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.setting_phot_std = QtWidgets.QGroupBox(Form)
        self.setting_phot_std.setCheckable(True)
        self.setting_phot_std.setObjectName("setting_phot_std")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.setting_phot_std)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.setting_phot_std_nomad = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_nomad.setChecked(True)
        self.setting_phot_std_nomad.setObjectName("setting_phot_std_nomad")
        self.gridLayout_3.addWidget(self.setting_phot_std_nomad, 0, 0, 1, 1)
        self.setting_phot_std_usno = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_usno.setChecked(True)
        self.setting_phot_std_usno.setObjectName("setting_phot_std_usno")
        self.gridLayout_3.addWidget(self.setting_phot_std_usno, 0, 1, 1, 1)
        self.setting_phot_std_gaia = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_gaia.setChecked(True)
        self.setting_phot_std_gaia.setObjectName("setting_phot_std_gaia")
        self.gridLayout_3.addWidget(self.setting_phot_std_gaia, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.setting_phot_std)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.setting_photo_std_radius = QtWidgets.QDoubleSpinBox(self.setting_phot_std)
        self.setting_photo_std_radius.setMinimum(1.0)
        self.setting_photo_std_radius.setMaximum(300.0)
        self.setting_photo_std_radius.setSingleStep(0.5)
        self.setting_photo_std_radius.setProperty("value", 10.0)
        self.setting_photo_std_radius.setObjectName("setting_photo_std_radius")
        self.gridLayout_3.addWidget(self.setting_photo_std_radius, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.setting_phot_std, 0, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(Form)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_44 = QtWidgets.QLabel(self.groupBox_15)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_15)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 1, 0, 1, 1)
        self.setting_phot_photpar_zmag = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.setting_phot_photpar_zmag.setMaximum(200.0)
        self.setting_phot_photpar_zmag.setProperty("value", 25.0)
        self.setting_phot_photpar_zmag.setObjectName("setting_phot_photpar_zmag")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_zmag, 1, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_15)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 2, 0, 1, 1)
        self.setting_phot_photpar_gain = QtWidgets.QLineEdit(self.groupBox_15)
        self.setting_phot_photpar_gain.setObjectName("setting_phot_photpar_gain")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_gain, 2, 1, 1, 1)
        self.setting_phot_photpar_aperture = QtWidgets.QLineEdit(self.groupBox_15)
        self.setting_phot_photpar_aperture.setObjectName("setting_phot_photpar_aperture")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_aperture, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_15, 0, 1, 2, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.setting_psf_sizeFactor = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.setting_psf_sizeFactor.setDecimals(1)
        self.setting_psf_sizeFactor.setMinimum(3.0)
        self.setting_psf_sizeFactor.setMaximum(50.0)
        self.setting_psf_sizeFactor.setProperty("value", 10.0)
        self.setting_psf_sizeFactor.setObjectName("setting_psf_sizeFactor")
        self.gridLayout.addWidget(self.setting_psf_sizeFactor, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.setting_psf_maxiter = QtWidgets.QSpinBox(self.groupBox_3)
        self.setting_psf_maxiter.setMinimum(3)
        self.setting_psf_maxiter.setMaximum(15)
        self.setting_psf_maxiter.setSingleStep(1)
        self.setting_psf_maxiter.setProperty("value", 10)
        self.setting_psf_maxiter.setObjectName("setting_psf_maxiter")
        self.gridLayout.addWidget(self.setting_psf_maxiter, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 2, 1)
        self.setting_ = QtWidgets.QGroupBox(Form)
        self.setting_.setObjectName("setting_")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.setting_)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_70 = QtWidgets.QLabel(self.setting_)
        self.label_70.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_6.addWidget(self.label_70, 0, 0, 1, 1)
        self.setting_phot_starf_max = QtWidgets.QSpinBox(self.setting_)
        self.setting_phot_starf_max.setMaximum(20000)
        self.setting_phot_starf_max.setProperty("value", 500)
        self.setting_phot_starf_max.setObjectName("setting_phot_starf_max")
        self.gridLayout_6.addWidget(self.setting_phot_starf_max, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.setting_, 2, 1, 1, 2)
        self.groupBox_31 = QtWidgets.QGroupBox(Form)
        self.groupBox_31.setObjectName("groupBox_31")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_31)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.setting_phot_hex_available = QtWidgets.QListWidget(self.groupBox_31)
        self.setting_phot_hex_available.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.setting_phot_hex_available.setObjectName("setting_phot_hex_available")
        self.gridLayout_7.addWidget(self.setting_phot_hex_available, 0, 0, 4, 1)
        self.setting_phot_hex_add = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_add.setObjectName("setting_phot_hex_add")
        self.gridLayout_7.addWidget(self.setting_phot_hex_add, 0, 1, 1, 1)
        self.setting_phot_hex_use = QtWidgets.QListWidget(self.groupBox_31)
        self.setting_phot_hex_use.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.setting_phot_hex_use.setObjectName("setting_phot_hex_use")
        self.gridLayout_7.addWidget(self.setting_phot_hex_use, 0, 2, 4, 1)
        self.setting_phot_hex_remove = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_remove.setObjectName("setting_phot_hex_remove")
        self.gridLayout_7.addWidget(self.setting_phot_hex_remove, 1, 1, 1, 1)
        self.setting_phot_hex_update = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_update.setObjectName("setting_phot_hex_update")
        self.gridLayout_7.addWidget(self.setting_phot_hex_update, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_31, 3, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(361, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 2)
        self.setting_phot_save = QtWidgets.QPushButton(Form)
        self.setting_phot_save.setMinimumSize(QtCore.QSize(72, 0))
        self.setting_phot_save.setMaximumSize(QtCore.QSize(72, 16777215))
        self.setting_phot_save.setObjectName("setting_phot_save")
        self.gridLayout_4.addWidget(self.setting_phot_save, 4, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Phometry Settings"))
        self.setting_phot_std.setTitle(_translate("Form", "S&tandard Magnitudes"))
        self.setting_phot_std_nomad.setText(_translate("Form", "NOMAD"))
        self.setting_phot_std_usno.setText(_translate("Form", "USNO"))
        self.setting_phot_std_gaia.setText(_translate("Form", "GAIA"))
        self.label_9.setText(_translate("Form", "Radius"))
        self.groupBox_15.setTitle(_translate("Form", "PhotPars"))
        self.label_44.setText(_translate("Form", "Aperture"))
        self.label_45.setText(_translate("Form", "ZMag"))
        self.label_57.setText(_translate("Form", "Gain"))
        self.setting_phot_photpar_gain.setText(_translate("Form", "gain"))
        self.setting_phot_photpar_aperture.setText(_translate("Form", "10.0,15.0"))
        self.groupBox_3.setTitle(_translate("Form", "PSF"))
        self.label.setText(_translate("Form", "Size Factor"))
        self.label_2.setText(_translate("Form", "MaxIter"))
        self.setting_.setTitle(_translate("Form", "Star Finder"))
        self.label_70.setText(_translate("Form", "Maximum Stars To find"))
        self.groupBox_31.setTitle(_translate("Form", "Extract From Header"))
        self.setting_phot_hex_add.setText(_translate("Form", ">>"))
        self.setting_phot_hex_remove.setText(_translate("Form", "<<"))
        self.setting_phot_hex_update.setText(_translate("Form", "Update List"))
        self.setting_phot_save.setText(_translate("Form", "Save"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
