# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\msh\OneDrive\Belgeler\the_myraf\gui\setting_photometry.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 448)
        self.gridLayout_8 = QtWidgets.QGridLayout(Form)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.setting_phot_std = QtWidgets.QGroupBox(Form)
        self.setting_phot_std.setMinimumSize(QtCore.QSize(201, 76))
        self.setting_phot_std.setMaximumSize(QtCore.QSize(16777215, 76))
        self.setting_phot_std.setCheckable(True)
        self.setting_phot_std.setObjectName("setting_phot_std")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.setting_phot_std)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.setting_phot_std_nomad = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_nomad.setChecked(True)
        self.setting_phot_std_nomad.setObjectName("setting_phot_std_nomad")
        self.gridLayout_3.addWidget(self.setting_phot_std_nomad, 0, 0, 1, 1)
        self.setting_phot_std_usno = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_usno.setChecked(True)
        self.setting_phot_std_usno.setObjectName("setting_phot_std_usno")
        self.gridLayout_3.addWidget(self.setting_phot_std_usno, 0, 1, 1, 1)
        self.setting_phot_std_gaia = QtWidgets.QCheckBox(self.setting_phot_std)
        self.setting_phot_std_gaia.setChecked(True)
        self.setting_phot_std_gaia.setObjectName("setting_phot_std_gaia")
        self.gridLayout_3.addWidget(self.setting_phot_std_gaia, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.setting_phot_std)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.setting_photo_std_radius = QtWidgets.QDoubleSpinBox(self.setting_phot_std)
        self.setting_photo_std_radius.setMinimum(1.0)
        self.setting_photo_std_radius.setMaximum(300.0)
        self.setting_photo_std_radius.setSingleStep(0.5)
        self.setting_photo_std_radius.setProperty("value", 10.0)
        self.setting_photo_std_radius.setObjectName("setting_photo_std_radius")
        self.gridLayout_3.addWidget(self.setting_photo_std_radius, 1, 1, 1, 2)
        self.gridLayout_8.addWidget(self.setting_phot_std, 0, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(Form)
        self.groupBox_20.setMinimumSize(QtCore.QSize(234, 79))
        self.groupBox_20.setMaximumSize(QtCore.QSize(16777215, 79))
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_65 = QtWidgets.QLabel(self.groupBox_20)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 0, 0, 1, 1)
        self.setting_phot_wcs_ra = QtWidgets.QLineEdit(self.groupBox_20)
        self.setting_phot_wcs_ra.setObjectName("setting_phot_wcs_ra")
        self.gridLayout_4.addWidget(self.setting_phot_wcs_ra, 0, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.groupBox_20)
        self.label_66.setObjectName("label_66")
        self.gridLayout_4.addWidget(self.label_66, 1, 0, 1, 1)
        self.setting_phot_wcs_dec = QtWidgets.QLineEdit(self.groupBox_20)
        self.setting_phot_wcs_dec.setObjectName("setting_phot_wcs_dec")
        self.gridLayout_4.addWidget(self.setting_phot_wcs_dec, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_20, 0, 1, 1, 2)
        self.groupBox_13 = QtWidgets.QGroupBox(Form)
        self.groupBox_13.setMinimumSize(QtCore.QSize(198, 79))
        self.groupBox_13.setMaximumSize(QtCore.QSize(16777215, 79))
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout.setObjectName("gridLayout")
        self.label_38 = QtWidgets.QLabel(self.groupBox_13)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 0, 0, 1, 1)
        self.setting_phot_datapar_exposure = QtWidgets.QLineEdit(self.groupBox_13)
        self.setting_phot_datapar_exposure.setObjectName("setting_phot_datapar_exposure")
        self.gridLayout.addWidget(self.setting_phot_datapar_exposure, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 1, 0, 1, 1)
        self.setting_phot_datapar_filter = QtWidgets.QLineEdit(self.groupBox_13)
        self.setting_phot_datapar_filter.setMaxLength(8)
        self.setting_phot_datapar_filter.setObjectName("setting_phot_datapar_filter")
        self.gridLayout.addWidget(self.setting_phot_datapar_filter, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(Form)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_47 = QtWidgets.QLabel(self.groupBox_17)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 0, 0, 1, 1)
        self.setting_phot_tlc_observatory = QtWidgets.QLineEdit(self.groupBox_17)
        self.setting_phot_tlc_observatory.setObjectName("setting_phot_tlc_observatory")
        self.gridLayout_5.addWidget(self.setting_phot_tlc_observatory, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_17)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 1, 0, 1, 1)
        self.setting_phot_tlc_time = QtWidgets.QLineEdit(self.groupBox_17)
        self.setting_phot_tlc_time.setObjectName("setting_phot_tlc_time")
        self.gridLayout_5.addWidget(self.setting_phot_tlc_time, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_17, 1, 1, 1, 2)
        self.groupBox_15 = QtWidgets.QGroupBox(Form)
        self.groupBox_15.setMinimumSize(QtCore.QSize(202, 105))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 105))
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_44 = QtWidgets.QLabel(self.groupBox_15)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 0, 0, 1, 1)
        self.setting_phot_photpar_aperture = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.setting_phot_photpar_aperture.setMinimum(1.0)
        self.setting_phot_photpar_aperture.setMaximum(100.0)
        self.setting_phot_photpar_aperture.setProperty("value", 10.0)
        self.setting_phot_photpar_aperture.setObjectName("setting_phot_photpar_aperture")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_aperture, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_15)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 1, 0, 1, 1)
        self.setting_phot_photpar_zmag = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.setting_phot_photpar_zmag.setMaximum(200.0)
        self.setting_phot_photpar_zmag.setProperty("value", 25.0)
        self.setting_phot_photpar_zmag.setObjectName("setting_phot_photpar_zmag")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_zmag, 1, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_15)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 2, 0, 1, 1)
        self.setting_phot_photpar_gain = QtWidgets.QLineEdit(self.groupBox_15)
        self.setting_phot_photpar_gain.setObjectName("setting_phot_photpar_gain")
        self.gridLayout_2.addWidget(self.setting_phot_photpar_gain, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_15, 2, 0, 1, 1)
        self.setting_ = QtWidgets.QGroupBox(Form)
        self.setting_.setMinimumSize(QtCore.QSize(221, 105))
        self.setting_.setMaximumSize(QtCore.QSize(16777215, 105))
        self.setting_.setObjectName("setting_")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.setting_)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_70 = QtWidgets.QLabel(self.setting_)
        self.label_70.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_6.addWidget(self.label_70, 0, 0, 1, 1)
        self.setting_phot_starf_max = QtWidgets.QSpinBox(self.setting_)
        self.setting_phot_starf_max.setMaximum(20000)
        self.setting_phot_starf_max.setProperty("value", 500)
        self.setting_phot_starf_max.setObjectName("setting_phot_starf_max")
        self.gridLayout_6.addWidget(self.setting_phot_starf_max, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.setting_, 2, 1, 1, 2)
        self.groupBox_31 = QtWidgets.QGroupBox(Form)
        self.groupBox_31.setObjectName("groupBox_31")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_31)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.setting_phot_hex_available = QtWidgets.QListWidget(self.groupBox_31)
        self.setting_phot_hex_available.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.setting_phot_hex_available.setObjectName("setting_phot_hex_available")
        self.gridLayout_7.addWidget(self.setting_phot_hex_available, 0, 0, 4, 1)
        self.setting_phot_hex_add = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_add.setObjectName("setting_phot_hex_add")
        self.gridLayout_7.addWidget(self.setting_phot_hex_add, 0, 1, 1, 1)
        self.setting_phot_hex_use = QtWidgets.QListWidget(self.groupBox_31)
        self.setting_phot_hex_use.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.setting_phot_hex_use.setObjectName("setting_phot_hex_use")
        self.gridLayout_7.addWidget(self.setting_phot_hex_use, 0, 2, 4, 1)
        self.setting_phot_hex_remove = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_remove.setObjectName("setting_phot_hex_remove")
        self.gridLayout_7.addWidget(self.setting_phot_hex_remove, 1, 1, 1, 1)
        self.setting_phot_hex_update = QtWidgets.QPushButton(self.groupBox_31)
        self.setting_phot_hex_update.setObjectName("setting_phot_hex_update")
        self.gridLayout_7.addWidget(self.setting_phot_hex_update, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_31, 3, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(361, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 4, 0, 1, 2)
        self.setting_phot_save = QtWidgets.QPushButton(Form)
        self.setting_phot_save.setMinimumSize(QtCore.QSize(72, 0))
        self.setting_phot_save.setMaximumSize(QtCore.QSize(72, 16777215))
        self.setting_phot_save.setObjectName("setting_phot_save")
        self.gridLayout_8.addWidget(self.setting_phot_save, 4, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Phometry Settings"))
        self.setting_phot_std.setTitle(_translate("Form", "Standard Magnitudes"))
        self.setting_phot_std_nomad.setText(_translate("Form", "NOMAD"))
        self.setting_phot_std_usno.setText(_translate("Form", "USNO"))
        self.setting_phot_std_gaia.setText(_translate("Form", "GAIA"))
        self.label_9.setText(_translate("Form", "Radius"))
        self.groupBox_20.setTitle(_translate("Form", "WCS"))
        self.label_65.setText(_translate("Form", "Right ascension"))
        self.setting_phot_wcs_ra.setText(_translate("Form", "ra"))
        self.label_66.setText(_translate("Form", "Declination"))
        self.setting_phot_wcs_dec.setText(_translate("Form", "dec"))
        self.groupBox_13.setTitle(_translate("Form", "DataPars"))
        self.label_38.setText(_translate("Form", "Exposur"))
        self.setting_phot_datapar_exposure.setText(_translate("Form", "exptime"))
        self.label_39.setText(_translate("Form", "Filter"))
        self.setting_phot_datapar_filter.setText(_translate("Form", "subset"))
        self.groupBox_17.setTitle(_translate("Form", "Location and Time"))
        self.label_47.setText(_translate("Form", "Observatory"))
        self.setting_phot_tlc_observatory.setText(_translate("Form", "observat"))
        self.label_48.setToolTip(_translate("Form", "If not give DATE-OBS"))
        self.label_48.setText(_translate("Form", "TIME-OBS"))
        self.setting_phot_tlc_time.setText(_translate("Form", "JD"))
        self.groupBox_15.setTitle(_translate("Form", "PhotPars"))
        self.label_44.setText(_translate("Form", "Aperture"))
        self.label_45.setText(_translate("Form", "ZMag"))
        self.label_57.setText(_translate("Form", "Gain"))
        self.setting_phot_photpar_gain.setText(_translate("Form", "gain"))
        self.setting_.setTitle(_translate("Form", "Star finder"))
        self.label_70.setText(_translate("Form", "Maximum Stars To find"))
        self.groupBox_31.setTitle(_translate("Form", "Extract From Header"))
        self.setting_phot_hex_add.setText(_translate("Form", ">>"))
        self.setting_phot_hex_remove.setText(_translate("Form", "<<"))
        self.setting_phot_hex_update.setText(_translate("Form", "Update List"))
        self.setting_phot_save.setText(_translate("Form", "Save"))

